tembak/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls, name = "admin"),
    path('', views.index, name = "index"),
    path('isi/', views.isi, name = "isi"),
    path('video/', include('video.urls')),


    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

video/urls.py
from django.contrib import admin
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from . import views

from django.views.static import serve
from django.conf.urls import url


app_name = 'video'
urlpatterns = [
    #listView
    path('', views.index, name = "index"),
    path('liat/', views.liat, name = "liat"),
    

    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

video/models.py
from django.db import models
from django.utils.text import slugify


class PostModel(models.Model):
    judul = models.CharField(max_length=255)
    ahem = models.CharField(max_length=255, default="aa")
    bhem = models.CharField(max_length=255, default="ba")
    

    def save(self, *args, **kwargs):
        super(PostModel, self).save(*args, **kwargs)

    def __str__(self):
        return "{}. {}".format(self.id, self.judul)
    

tembak/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username', 
            'email', 
            'password1', 
            'password2',
        ]
        

video/forms.py
from django import forms

from .models import PostModel

class PostForm(forms.ModelForm):
        class Meta:
                model = PostModel
                fields = [
                        'judul',

                ]

tembak/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import TemplateView

from django.contrib.auth import authenticate, login as dji_login, logout as dji_logout
from django.contrib.auth.forms import UserCreationForm

from django.contrib import messages
from .forms import CreateUserForm

def index(request):
    context = {
        'Judul' : 'ATTA',
        'Content' : 'Silahkan Log in',
    }

    if request.method == "POST":
        username_login = request.POST['username']
        password_login = request.POST['password']
        user = authenticate(request, username=username_login, password=password_login)
        
        if user is not None:
            dji_login(request,user)
            return redirect('isi')
        else:
            messages.error(request, "Username/Password Tidak Cocok Coba Lagi")
    return render(request, 'index.html', context)

def isi(request):
    context = {
        'Judul' : 'ATTA',
        'Content' : 'Silahkan Log in',
    }

    return render(request, 'isi.html', context)

video/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from .forms import PostForm
from .models import PostModel


# Create your views here.
def index(request):
    contact_form = PostForm()

    if request.method == 'POST':
        PostModel.objects.create(
            judul 		= request.POST.get('judul'),
        )
        return redirect('index')

    context = {
        'Judul' : 'ATTA',
        'Content' : '',
        'contact_form' : contact_form,
    }

    return render(request, 'video.html', context)

def liat(request):
    postmodel = PostModel.objects.all()
    context = {
        'Judul' : 'ATTA',
        'Content' : '',
        'posts' : postmodel,
    }
    return render(request, 'liat.html', context)
    

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        
        {% block title %}
            
        {% endblock title %} 

    </title>

    {% block css %}
            
    {% endblock css %} 

    {%include "snippets/styles.html"%}

</head>
<body>
    
        {% block contents %}
        
        {% endblock contents %}
    

    
        {% block contents2 %}
        
        {% endblock contents2 %}
    
    
    {% block js %}
        
    {% endblock js %}
        
    {%include "snippets/scripts.html"%}
    
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
    {{Judul}}    
{% endblock title %}

{% block css %}
    <style>

        body{
            background-color: royalblue !important;
        }

        .hai{
            margin: 3% auto 0.5%;
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            font-weight: bold;
            text-align: center;
            overflow: hidden;
            opacity: 0%;
        }

        .animationhai {
            animation: animationhai 10s ease-in 1 reverse forwards;
            animation-delay: 0.5s;
            
        }
        
        @keyframes animationhai{
            0% {
                opacity: 0%;
            }

            45%{
                opacity: 100%;
            }

            75% {
                margin: 3% auto 0.5%;
                opacity: 100%;
            }
        
            100% {
                margin: 5% auto 0.5%;
                opacity: 0%;
            }
        }

        .dibawahhai{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            position: relative;
            font-weight: bold;
            text-align: center;
            opacity: 0%;
        }

        .animationdibawahhai {
            animation: animationdibawahhai 7.5s ease-in 1 reverse forwards;
            animation-delay: 2.5s;
            
        }
        
        @keyframes animationdibawahhai{
            0% {
                opacity: 0%;
            }

            45%{
                opacity: 100%;
            }

            75% {
                margin: 0%;
                opacity: 100%;
            }
        
            100% {
                margin: 3%;
                opacity: 0%;
            }
        }

        .kotak{
            background-color: rgb(236, 28, 28);
            text-align: center;
            width: 45%;
            margin: 2% auto 0%;
            opacity: 0%;
            border-radius: 0%;
        }

        .animationkotak {
            animation: animationkotak 5s ease-in 1 reverse forwards;
            animation-delay: 6s;
            
        }
        
        @keyframes animationkotak{
            0%{
                margin: -3% auto 0%;
                opacity: 100%;
                border-radius: 3%;
            }

            60% {
                opacity: 100%;
                margin: 2% auto 0%;
                border-radius: 0%;
            }
        
            100% {
                opacity: 0%;
                margin: 2% auto 0%;
                border-radius: 0%;
            }
        }

        .kotak .memastikan{
            text-align: left;
        }

        .buttonlogin{
            margin-top: 2%;
        }
    </style>
{% endblock css %}

{% block contents %}
    <h1 class="hai animationhai">HAI HAI HALO</h1>
    <h2 class="dibawahhai animationdibawahhai ">Park Atta Halilintar Ashiap Nusa <br> Permata Siburian Jimin</h2>

    <div class="kotak animationkotak">
        <div class="form">
            <h1 class="tulisanlogin">Verifikasi</h1>
            <h4 class="memastikan">Untuk memastikan anda adalah atta masukkan nama dosen pa dan password hp anda</h4>
            <form class="login" method="POST">
                {% csrf_token %}
                <label class="label" for="username">Nama Dosen PA (*misal riadi): </label>
                <br>
                <input class="isiian" type="text" name="username" id="username">
                <br>
                <label class="label" for="password">Password HP: </label>
                <br>
                <input class="isiian" type="password" name="password" id="password">
                <br>
                <button type ="submit" class="buttonlogin">Login</button>
            </form>
        </div>
    </div>

    {%if messages%}
        {%for message in messages%}
        <div class="pesanerror">
            <h3 class="tulisanpesanerror">
                {{message}}
            </h3>
        </div>
        {% endfor %}
    {% endif %}
    

{% endblock contents %}

{% block js %}
    
{% endblock js %}

    

    
    

templates/isi.html
{% extends 'base.html' %}

{% block title %}
    {{Judul}}    
{% endblock title %}

{% block css %}
    <style>

        *{
            text-align: center;
        }

        body{
            background-color: royalblue !important;
        }

        .kata{
            opacity: 0%;
        }

        .paragraf1{
            margin-top: 5%;
        }

        .animationparagraf1 {
            animation: animationparagraf1 2s ease-in 1 reverse forwards;
            animation-delay: 0.5s;
            
        }
        
        @keyframes animationparagraf1{
            0% {
                margin: 5% auto 0.5%;
                opacity: 100%;
            }
            
            100% {
                margin: 7% auto 0.5%;
                opacity: 0%;
            }
        }

        .animationparagraf2 {
            animation: animationparagraf2 2s ease-in 1 reverse forwards;
            animation-delay: 3s;
            
        }
        
        @keyframes animationparagraf2{
            0% {
                margin-top: 0.5%;
                opacity: 100%;
            }
            
            100% {
                margin-top: 3%;
                opacity: 0%;
            }
        }

        .animationparagraf3 {
            animation: animationparagraf3 2s ease-in 1 reverse forwards;
            animation-delay: 6.5s;
            
        }
        
        @keyframes animationparagraf3{
            0% {
                margin-top: 0.5%;
                opacity: 100%;
            }
            
            100% {
                margin-top: 3%;
                opacity: 0%;
            }
        }

        .animationparagraf4 {
            animation: animationparagraf4 2s ease-in 1 reverse forwards;
            animation-delay: 10s;
            
        }
        
        @keyframes animationparagraf4{
            0% {
                margin-top: 0.5%;
                opacity: 100%;
            }
            
            100% {
                margin-top: 3%;
                opacity: 0%;
            }
        }

        .animationparagraf5 {
            animation: animationparagraf5 2s ease-in 1 reverse forwards;
            animation-delay: 14s;
            
        }
        
        @keyframes animationparagraf5{
            0% {
                margin-top: 0.5%;
                opacity: 100%;
            }
            
            100% {
                margin-top: 3%;
                opacity: 0%;
            }
        }

        .tombollogin{
            background-color: wheat;
            width: 10%;
            text-decoration: none;
            margin: auto;
        }

        .animationlogin {
            animation: animationlogin 2s ease-in 1 reverse forwards;
            animation-delay: 17s;
            
        }
        
        @keyframes animationlogin{
            0% {
                margin-top: 0.5%;
                opacity: 100%;
            }
            
            100% {
                margin-top: 3%;
                opacity: 0%;
            }
        }

    </style>
{% endblock css %}

{% block contents %}
    <h1 class="paragraf1 kata animationparagraf1">HAI PERKENALKAN INI AKU SI "A"</h1>
    <h2 class="paragraf2 kata animationparagraf2">Maaf Belakangan ini Hadir ku Malah Menambah Beban Pikiranmu</h2>
    <h2 class="paragraf3 kata animationparagraf3">Maaf Juga karna aku mungkin Kau Kehilangan Seorang Teman</h2>
    <h2 class="paragraf4 kata animationparagraf4">Tapi Mulai Sekarang ku ingin Hadirku Membawa Tawa bagimu</h2>
    <h2 class="paragraf5 kata animationparagraf5">Dah itu yk sih wkwk, ohh iya aku mau menyatakan sesuatu</h2>

    {% load static %}
    <a class="nav-link" href="{% url 'video:index' %}">
        <h3 class="tombollogin kata animationlogin">
            Lanjut
        </h3>
    </a>
{% endblock contents %}

{% block js %}
    
{% endblock js %}

    

    
    

templates/liat.html
{% extends 'base.html' %}

{% block static %}
    {% load static %}
{% endblock static %}

{% block title %}
    {{Judul}}    
{% endblock title %}

{% block css %}
    
{% endblock css %}

{% block contents %}

    {% for post in posts %}
        
        <h1>{{post.judul}}</h1>
        
    {% endfor %}

{% endblock contents %}

{% block js %}
    
{% endblock js %}

    

    
    

templates/snippets/scripts.html
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
   
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

templates/snippets/styles.html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

templates/video.html
{% extends 'base.html' %}

{% block static %}
    {% load static %}
{% endblock static %}

{% block title %}
    {{Judul}}    
{% endblock title %}

{% block css %}
    <style>
        body{
            background-color: black !important;
            position: relative;
        }

        video{
            margin-top: 8%;
            width: 60%;
            z-index: 1;
        }

        h1{
            color: white;
            
            width: 75%;
            text-align: right;
            margin: auto;
            position: absolute;
            opacity: 0%;
        }

        .kata1{
            margin-top: 10%;
        }

        .animationkata1 {
            animation: animationkata1 2s ease-in 1 reverse forwards;
            animation-delay: 17s;
            
        }
        
        @keyframes animationkata1{
            0% {
                opacity: 100%;
            }
            
            100% {
                opacity: 0%;
            }
        }

        .kata2{
            margin-top: 15%;
        }

        .animationkata2 {
            animation: animationkata2 2s ease-in 1 reverse forwards;
            animation-delay: 35s;
            
        }
        
        @keyframes animationkata2{
            0% {
                opacity: 100%;
            }
            
            100% {
                opacity: 0%;
            }
        }

        .kata3{
            margin-top: 20%;
        }

        .animationkata3 {
            animation: animationkata3 2s ease-in 1 reverse forwards;
            animation-delay: 60s;
            
        }
        
        @keyframes animationkata3{
            0% {
                opacity: 100%;
            }
            
            100% {
                opacity: 0%;
            }
        }

        .kata4{
            margin-top: 25%;
        }

        .animationkata4 {
            animation: animationkata4 2s ease-in 1 reverse forwards;
            animation-delay: 90s;
            
        }
        
        @keyframes animationkata4{
            0% {
                opacity: 100%;
            }
            
            100% {
                opacity: 0%;
            }
        }

        .jawaban{
            position: absolute;
            opacity: 0%;
            margin-left: 55%;
            margin-top: 31%;
            z-index: 5;
        }

        .nembak{
            color: cornsilk;
        }

        .tombol{
            text-align: right;
        }

        .animationjawaban {
            animation: animationjawaban 2s ease-in 1 reverse forwards;
            animation-delay: 100s;
            
        }
        
        @keyframes animationjawaban{
            0% {
                opacity: 100%;
            }
            
            100% {
                opacity: 0%;
            }
        }

    </style>
{% endblock css %}

{% block contents %}
    <div class="kata">
        <h1 class="kata1 animationkata1">I</h1>
        <h1 class="kata2 animationkata2">LOVE</h1>
        <h1 class="kata3 animationkata3">YOU</h1>
        <h1 class="kata4 animationkata4">SO MUCH</h1>

    </div>

    <form method="POST"  class="jawaban animationjawaban">
        {% csrf_token %}
        <div class="form-group">
            <h3 class="nembak">
                Pacaran Skuy?
            </h3>
            {{contact_form.judul}}
        </div>
    
        <button type="submit" class="tombol">
            Kirim
        </button>
    </form>  
    
    <video autoplay loop class="video">
        <source src="{% static 'images/attavideo.mp4' %}" type="video/mp4">
        
    </video>

    <!-- <video src="{% static 'images/smoke.mp4' %}" muted="" autoplay=""></video> -->

{% endblock contents %}

{% block js %}
    
{% endblock js %}

    

    
    